import type { CourseResult, StudentRecord } from "@/types/academic"

export const schoolName = "OHEKURU Health Educational Center, Rano"

export const classStudents: StudentRecord[] = [
  {
    matricNo: "UG25/OHEKURU/1001",
    fullName: "Salamatu Bako",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 3,
    cgpa: 3,
    firstSemester: {
      paper1: 13,
      paper2: 10,
      paper3: 12,
      ca: 14,
      exam: 35,
      totalScore: 84,
      grade: "C",
      gradePoint: 3,
      gpa: 3,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1002",
    fullName: "Binta Gambo",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 2,
    cgpa: 2,
    firstSemester: {
      paper1: 7,
      paper2: 6,
      paper3: 25,
      ca: 4,
      exam: 28,
      totalScore: 70,
      grade: "D",
      gradePoint: 2,
      gpa: 2,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1003",
    fullName: "Jamima S. Bargi",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 4,
    cgpa: 4,
    firstSemester: {
      paper1: 17,
      paper2: 12,
      paper3: 12,
      ca: 17,
      exam: 30,
      totalScore: 88,
      grade: "B",
      gradePoint: 4,
      gpa: 4,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1004",
    fullName: "Isah Bulus",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 3,
    cgpa: 3,
    firstSemester: {
      paper1: 10,
      paper2: 10,
      paper3: 9,
      ca: 13,
      exam: 34,
      totalScore: 76,
      grade: "C",
      gradePoint: 3,
      gpa: 3,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1005",
    fullName: "Saminu Kadiri",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 4,
    cgpa: 4,
    firstSemester: {
      paper1: 10,
      paper2: 14,
      paper3: 10,
      ca: 15,
      exam: 36,
      totalScore: 85,
      grade: "B",
      gradePoint: 4,
      gpa: 4,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1006",
    fullName: "Hannatu Illiya",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 2,
    cgpa: 2,
    firstSemester: {
      paper1: 10,
      paper2: 9,
      paper3: 5,
      ca: 10,
      exam: 31,
      totalScore: 65,
      grade: "D",
      gradePoint: 2,
      gpa: 2,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1007",
    fullName: "Hannatu Sai'du",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 2,
    cgpa: 2,
    firstSemester: {
      paper1: 13,
      paper2: 13,
      paper3: 14,
      ca: 10,
      exam: 20,
      totalScore: 70,
      grade: "D",
      gradePoint: 2,
      gpa: 2,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1008",
    fullName: "Christana Rabo",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 5,
    cgpa: 5,
    firstSemester: {
      paper1: 13,
      paper2: 12,
      paper3: 14,
      ca: 16,
      exam: 40,
      totalScore: 95,
      grade: "A",
      gradePoint: 5,
      gpa: 5,
    },
    secondSemesterStatus: "Awaiting",
  },
  {
    matricNo: "UG25/OHEKURU/1009",
    fullName: "Maryam Ibrahim",
    department: "Health Education",
    faculty: "Health Sciences",
    level: 200,
    gpa: 2,
    cgpa: 2,
    firstSemester: {
      paper1: 10,
      paper2: 9,
      paper3: 9,
      ca: 10,
      exam: 29,
      totalScore: 67,
      grade: "D",
      gradePoint: 2,
      gpa: 2,
    },
    secondSemesterStatus: "Awaiting",
  },
]

export const demoStudent = classStudents[0]

export function resultsForStudent(student: StudentRecord): CourseResult[] {
  return [
  {
    courseCode: "PAPER 1",
    title: "First semester paper 1",
    unit: 0,
      score: student.firstSemester.paper1,
    grade: "",
    gradePoint: 0,
    semester: "First",
  },
  {
    courseCode: "PAPER 2",
    title: "First semester paper 2",
    unit: 0,
      score: student.firstSemester.paper2,
    grade: "",
    gradePoint: 0,
    semester: "First",
  },
  {
    courseCode: "PAPER 3",
    title: "First semester paper 3",
    unit: 0,
      score: student.firstSemester.paper3,
    grade: "",
    gradePoint: 0,
    semester: "First",
  },
  {
    courseCode: "CA",
    title: "Continuous assessment",
    unit: 0,
      score: student.firstSemester.ca,
    grade: "",
    gradePoint: 0,
    semester: "First",
  },
  {
    courseCode: "EXAM",
    title: "First semester examination",
    unit: 0,
      score: student.firstSemester.exam,
    grade: "",
    gradePoint: 0,
    semester: "First",
  },
  {
    courseCode: "TOTAL",
    title: "First semester total score",
    unit: 1,
      score: student.firstSemester.totalScore,
      grade: student.firstSemester.grade,
      gradePoint: student.firstSemester.gradePoint,
    semester: "First",
  },
  ]
}

export const demoResults = resultsForStudent(demoStudent)

export const classFirstSemesterResults: CourseResult[] = classStudents.map((student) => ({
  courseCode: student.matricNo.replace("UG25/OHEKURU/", ""),
  title: student.fullName,
  unit: 1,
  score: student.firstSemester.totalScore,
  grade: student.firstSemester.grade,
  gradePoint: student.firstSemester.gradePoint,
  semester: "First",
}))

export const gpaTrend = [{ label: "First Sem", gpa: demoStudent.gpa }]

export const departmentPerformance = [
  {
    label: "Health Education",
    value:
      classStudents.reduce((total, student) => total + student.firstSemester.gpa, 0) /
      classStudents.length,
  },
  { label: "Second Semester", value: 0 },
  { label: "Registered Students", value: classStudents.length },
  { label: "Published Results", value: classStudents.length },
]
